version: "3.7"

services:
  websocket:
    build:
      context: ./comet
      dockerfile: Dockerfile
    image: 你的仓库/middleware-team/notify-center-comet:${VERSION}
    ports:
      - 20606:8081
    deploy:
      update_config:
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 1024M
  webapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: 你的仓库/middleware-team/notify-center-server:${VERSION}
    ports:
      - 20607:8080
    deploy:
      update_config:
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 1024M
