version: "3.7"

services:
  websocket:
    build:
      context: ./comet
      dockerfile: Dockerfile
    image: docker.jsjit.cn/middleware-team/notify-center-comet:v2-${VERSION}
    ports:
      - 20606:8081
    deploy:
      replicas: 1
      update_config:
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 1024M
  webapi:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: docker.jsjit.cn/middleware-team/notify-center-server:v2-${VERSION}
    ports:
      - 20607:8080
    environment:
      GIN_MODE: ${GIN_MODE}
    deploy:
      replicas: 1
      update_config:
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 3
      resources:
        limits:
          memory: 1024M
